export const SEED_USERS = [
  {
    name: 'Dr. Rajesh Natarajan',
    email: 'admin@wildsense.org',
    phone: '+91 98450 11223',
    password: 'password123',
    role: 'admin',
    location: { name: 'Bandipur Range HQ', latitude: 11.6664, longitude: 76.6295 },
    assignedZone: 'Central Command & Control Center',
    badgeNumber: 'FD-CMD-001',
  },
  {
    name: 'Officer Priya Sharma',
    email: 'officer@wildsense.org',
    phone: '+91 98450 44556',
    password: 'password123',
    role: 'officer',
    location: { name: 'Gundlupet Buffer Range', latitude: 11.6912, longitude: 76.6854 },
    assignedZone: 'Sector Alpha - North Corridor',
    badgeNumber: 'FD-RFO-104',
  },
  {
    name: 'Ranger Vikram Gowda',
    email: 'vikram.gowda@wildsense.org',
    phone: '+91 98450 77889',
    password: 'password123',
    role: 'officer',
    location: { name: 'Mangala Forest Outpost', latitude: 11.6521, longitude: 76.6124 },
    assignedZone: 'Sector Beta - Southern Boundary',
    badgeNumber: 'FD-RGR-209',
  },
  {
    name: 'Officer Anand Kumar',
    email: 'anand.kumar@wildsense.org',
    phone: '+91 98450 33221',
    password: 'password123',
    role: 'officer',
    location: { name: 'Hangala Rapid Patrol Base', latitude: 11.6845, longitude: 76.6432 },
    assignedZone: 'Sector Gamma - Agricultural Buffer',
    badgeNumber: 'FD-RFO-312',
  },
  {
    name: 'Ranger Sunita Murthy',
    email: 'sunita.murthy@wildsense.org',
    phone: '+91 98450 99887',
    password: 'password123',
    role: 'officer',
    location: { name: 'Moyar Gorge Checkpost', latitude: 11.6214, longitude: 76.6712 },
    assignedZone: 'Sector Delta - River Corridor',
    badgeNumber: 'FD-RGR-405',
  },
  {
    name: 'Ramesh Patel',
    email: 'resident@wildsense.org',
    phone: '+91 94481 22334',
    password: 'password123',
    role: 'resident',
    location: { name: 'Mangala Village - Farm Sector 3', latitude: 11.6548, longitude: 76.6178, radiusKm: 3 },
    assignedZone: 'Mangala Village',
  },
  {
    name: 'Kavitha Hegde',
    email: 'kavitha.hegde@wildsense.org',
    phone: '+91 94481 55667',
    password: 'password123',
    role: 'resident',
    location: { name: 'Gundlupet Fringe - Hamlet 2', latitude: 11.6885, longitude: 76.6792, radiusKm: 3 },
    assignedZone: 'Gundlupet Fringe',
  },
  {
    name: 'Suresh Gowda',
    email: 'suresh.gowda@wildsense.org',
    phone: '+91 94481 88990',
    password: 'password123',
    role: 'resident',
    location: { name: 'Hangala Village - West Fields', latitude: 11.6812, longitude: 76.6385, radiusKm: 4 },
    assignedZone: 'Hangala Village',
  },
  {
    name: 'Manjula Rao',
    email: 'manjula.rao@wildsense.org',
    phone: '+91 94481 11225',
    password: 'password123',
    role: 'resident',
    location: { name: 'Bandipur Gate Settlement', latitude: 11.6625, longitude: 76.6315, radiusKm: 2 },
    assignedZone: 'Bandipur Gate',
  },
];

export const SEED_SENSORS = [
  {
    sensorId: 'SEN-CAM-101',
    name: 'Thermal Camera Hub Alpha',
    type: 'Thermal Camera',
    locationName: 'North Forest Perimeter - Tower 1',
    latitude: 11.6782,
    longitude: 76.6214,
    batteryLevel: 94,
    signalStrength: 92,
    connectivity: 'online',
    status: 'active',
    solarCharging: true,
    temperature: 25.8,
    sensitivity: 'High',
  },
  {
    sensorId: 'SEN-PIR-102',
    name: 'PIR Motion Sensor Alpha-2',
    type: 'PIR Motion Sensor',
    locationName: 'Mangala Elephant Corridor Path',
    latitude: 11.6591,
    longitude: 76.6152,
    batteryLevel: 88,
    signalStrength: 85,
    connectivity: 'online',
    status: 'active',
    solarCharging: true,
    temperature: 26.2,
    sensitivity: 'High',
  },
  {
    sensorId: 'SEN-MIC-103',
    name: 'Acoustic Triangulation Sensor A3',
    type: 'Acoustic Sensor',
    locationName: 'Hangala Stream Buffer',
    latitude: 11.6824,
    longitude: 76.6355,
    batteryLevel: 79,
    signalStrength: 80,
    connectivity: 'online',
    status: 'active',
    solarCharging: true,
    temperature: 24.9,
    sensitivity: 'Ultra',
  },
  {
    sensorId: 'SEN-CAM-104',
    name: 'Dual-Spectrum AI Camera 4',
    type: 'Optical Camera',
    locationName: 'Gundlupet Agricultural Boundary',
    latitude: 11.6895,
    longitude: 76.6741,
    batteryLevel: 96,
    signalStrength: 95,
    connectivity: 'online',
    status: 'active',
    solarCharging: true,
    temperature: 27.1,
    sensitivity: 'High',
  },
  {
    sensorId: 'SEN-PIR-105',
    name: 'PIR Infrared Sensor Beta-1',
    type: 'PIR Motion Sensor',
    locationName: 'Tiger Trail Waterhole Crossing',
    latitude: 11.6445,
    longitude: 76.6291,
    batteryLevel: 42,
    signalStrength: 68,
    connectivity: 'weak',
    status: 'warning',
    solarCharging: true,
    temperature: 28.3,
    sensitivity: 'Medium',
    notes: 'Partial canopy shade affecting solar panel efficiency during afternoons.',
  },
  {
    sensorId: 'SEN-SEIS-106',
    name: 'Seismic Footstep Array 1',
    type: 'Seismic Sensor',
    locationName: 'Elephant Pass Valley Ridge',
    latitude: 11.6512,
    longitude: 76.6482,
    batteryLevel: 91,
    signalStrength: 88,
    connectivity: 'online',
    status: 'active',
    solarCharging: true,
    temperature: 25.1,
    sensitivity: 'Ultra',
  },
  {
    sensorId: 'SEN-CAM-107',
    name: 'Thermal Camera Hub Beta',
    type: 'Thermal Camera',
    locationName: 'South Riverbank Ingress Point',
    latitude: 11.6321,
    longitude: 76.6625,
    batteryLevel: 85,
    signalStrength: 82,
    connectivity: 'online',
    status: 'active',
    solarCharging: true,
    temperature: 26.4,
    sensitivity: 'High',
  },
  {
    sensorId: 'SEN-PIR-108',
    name: 'PIR Motion Sensor Gamma-3',
    type: 'PIR Motion Sensor',
    locationName: 'Forest Gate West Boundary Fence',
    latitude: 11.6715,
    longitude: 76.6089,
    batteryLevel: 15,
    signalStrength: 45,
    connectivity: 'weak',
    status: 'warning',
    solarCharging: false,
    temperature: 29.0,
    sensitivity: 'High',
    notes: 'Battery replacement scheduled for ranger team.',
  },
  {
    sensorId: 'SEN-GPS-109',
    name: 'LoRa Collar Gateway Node',
    type: 'GPS Module',
    locationName: 'Central Forest Watchtower Top',
    latitude: 11.6664,
    longitude: 76.6295,
    batteryLevel: 100,
    signalStrength: 99,
    connectivity: 'online',
    status: 'active',
    solarCharging: true,
    temperature: 24.5,
    sensitivity: 'High',
  },
  {
    sensorId: 'SEN-CAM-110',
    name: 'Optical Night Vision Cam 6',
    type: 'Optical Camera',
    locationName: 'East Sugar Cane Field Buffer',
    latitude: 11.6795,
    longitude: 76.6892,
    batteryLevel: 0,
    signalStrength: 0,
    connectivity: 'offline',
    status: 'maintenance',
    solarCharging: false,
    temperature: 23.0,
    sensitivity: 'Low',
    notes: 'Firmware reset and solar wire repair in progress.',
  },
];
